// <auto-generated />
using System;
using BioInfoProject.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioInfoProject.Server.Migrations
{
    [DbContext(typeof(BioInfoDbContext))]
    [Migration("20260519184120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("BioInfoProject.Server.Entities.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("MaxDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("MinDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Datasets", (string)null);
                });

            modelBuilder.Entity("BioInfoProject.Server.Entities.EpidemiologicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("CumulativeCases")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CumulativeDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateReported")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewCases")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhoRegion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("DatasetId", "Country");

                    b.HasIndex("DatasetId", "DateReported");

                    b.HasIndex("DatasetId", "WhoRegion");

                    b.ToTable("EpidemiologicalRecords", (string)null);
                });

            modelBuilder.Entity("BioInfoProject.Server.Entities.EpidemiologicalRecord", b =>
                {
                    b.HasOne("BioInfoProject.Server.Entities.Dataset", "Dataset")
                        .WithMany("Records")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("BioInfoProject.Server.Entities.Dataset", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
